./sim_define.v
#/../../src/rtl/refCPU/rev00_protect/ASYNC_RAM_DP_WBE.v
#../../src/rtl/refCPU/rev00_protect/reg_file_async.v
#../../src/rtl/refCPU/rev00_protect/rv32i_single_cycle_cpu_protected.vp
#../../src/rtl/refCPU/rev00_protect/RV32I_System.v

../../testbench/cpu_tb.v
../../../source/myCPU/rev00/datapath.sv
../../../source/myCPU/rev00/maindec.sv
../../../source/myCPU/rev00/branch_logic.sv
../../../source/myCPU/rev00/aludec.sv
../../../source/myCPU/rev00/alu.sv
../../../source/myCPU/rev00/controller.sv
../../../source/myCPU/rev00/riscvsingle.sv
../../../source/myCPU/rev00/building_blocks/mux3.sv
../../../source/myCPU/rev00/building_blocks/adder.sv
../../../source/myCPU/rev00/building_blocks/mux2.sv
../../../source/myCPU/rev00/building_blocks/extend.sv
../../../source/myCPU/rev00/building_blocks/flopr.sv
../../../source/myCPU/rev00/building_blocks/flopenr.sv
../../../source/myCPU/rev00/building_blocks/be_logic.sv
../../../source/myCPU/rev00/SMU_RV32I_System.v
../../../source/myCPU/rev00/reg_file_async.v
../../../source/myCPU/rev00/ASYNC_RAM_DP_WBE.v
../../../source/myCPU/rev00/register_FD.sv
../../../source/myCPU/rev00/register_DE.sv
../../../source/myCPU/rev00/register_EM.sv
../../../source/myCPU/rev00/register_MW.sv
../../../source/myCPU/rev00/Hazard_unit.sv
